# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_show.ui'
#
# Created: Mon Feb 20 21:09:10 2012
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(621, 454)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setBaseSize(QtCore.QSize(10, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.search_input = QtGui.QLineEdit(self.groupBox_3)
        self.search_input.setText(_fromUtf8(""))
        self.search_input.setObjectName(_fromUtf8("search_input"))
        self.horizontalLayout.addWidget(self.search_input)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.logs_table = QtGui.QTableView(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logs_table.sizePolicy().hasHeightForWidth())
        self.logs_table.setSizePolicy(sizePolicy)
        self.logs_table.setAutoFillBackground(True)
        self.logs_table.setFrameShape(QtGui.QFrame.StyledPanel)
        self.logs_table.setAlternatingRowColors(True)
        self.logs_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.logs_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.logs_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.logs_table.setGridStyle(QtCore.Qt.DashLine)
        self.logs_table.setSortingEnabled(True)
        self.logs_table.setObjectName(_fromUtf8("logs_table"))
        self.logs_table.horizontalHeader().setCascadingSectionResizes(True)
        self.logs_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.logs_table)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 2, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.notify_type = QtGui.QCheckBox(self.groupBox)
        self.notify_type.setObjectName(_fromUtf8("notify_type"))
        self.verticalLayout.addWidget(self.notify_type)
        self.notify_warn = QtGui.QCheckBox(self.groupBox)
        self.notify_warn.setObjectName(_fromUtf8("notify_warn"))
        self.verticalLayout.addWidget(self.notify_warn)
        self.notify_error = QtGui.QCheckBox(self.groupBox)
        self.notify_error.setObjectName(_fromUtf8("notify_error"))
        self.verticalLayout.addWidget(self.notify_error)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.start_datetime = QtGui.QDateTimeEdit(self.groupBox_2)
        self.start_datetime.setEnabled(False)
        self.start_datetime.setAccelerated(False)
        self.start_datetime.setObjectName(_fromUtf8("start_datetime"))
        self.gridLayout.addWidget(self.start_datetime, 1, 1, 1, 1)
        self.end_datetime = QtGui.QDateTimeEdit(self.groupBox_2)
        self.end_datetime.setEnabled(False)
        self.end_datetime.setDate(QtCore.QDate(2012, 1, 1))
        self.end_datetime.setObjectName(_fromUtf8("end_datetime"))
        self.gridLayout.addWidget(self.end_datetime, 2, 1, 1, 1)
        self.date_filter = QtGui.QCheckBox(self.groupBox_2)
        self.date_filter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_filter.setAutoFillBackground(False)
        self.date_filter.setChecked(False)
        self.date_filter.setAutoRepeat(False)
        self.date_filter.setAutoExclusive(False)
        self.date_filter.setObjectName(_fromUtf8("date_filter"))
        self.gridLayout.addWidget(self.date_filter, 3, 0, 1, 2)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 10)
        self.gridLayout_2.setRowStretch(1, 10)
        self.gridLayout_2.setRowStretch(2, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Close = QtGui.QAction(MainWindow)
        self.action_Close.setObjectName(_fromUtf8("action_Close"))
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Close)
        self.menubar.addAction(self.menu_File.menuAction())
        self.label.setBuddy(self.start_datetime)
        self.label_2.setBuddy(self.end_datetime)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Close, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.date_filter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.start_datetime.setEnabled)
        QtCore.QObject.connect(self.date_filter, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.end_datetime.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.search_input, self.notify_type)
        MainWindow.setTabOrder(self.notify_type, self.notify_warn)
        MainWindow.setTabOrder(self.notify_warn, self.notify_error)
        MainWindow.setTabOrder(self.notify_error, self.date_filter)
        MainWindow.setTabOrder(self.date_filter, self.start_datetime)
        MainWindow.setTabOrder(self.start_datetime, self.end_datetime)
        MainWindow.setTabOrder(self.end_datetime, self.logs_table)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Search world", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Warn Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.notify_type.setText(QtGui.QApplication.translate("MainWindow", "Notify", None, QtGui.QApplication.UnicodeUTF8))
        self.notify_warn.setText(QtGui.QApplication.translate("MainWindow", "Warning", None, QtGui.QApplication.UnicodeUTF8))
        self.notify_error.setText(QtGui.QApplication.translate("MainWindow", "Error", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Date Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.start_datetime.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.end_datetime.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "dd.MM.yyyy HH:mm", None, QtGui.QApplication.UnicodeUTF8))
        self.date_filter.setText(QtGui.QApplication.translate("MainWindow", "Active Date Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Start Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "End Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Close.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

